poll/poll/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('polls/', include('polls.urls'))
]

poll/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [ 
	path('',views.index,name='index'),
        path('<int:faculty_id>/',views.detail,name='detail'),# /polls/5
        path('<int:faculty_id>/results' ,views.results,name='results'),
        path('<int:faculty_id>/vote',views.vote,name="vote"),
]

poll/polls/models.py
from django.db import models

# Create your models here.

class Faculty(models.Model):
    faculty_name = models.CharField(max_length= 50)
    faculty_dept = models.CharField(max_length=5)
    def __str__(self):
        return self.faculty_name

class Choice(models.Model):
    faculty= models.ForeignKey(Faculty, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length =50)
    votes =models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

poll/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Faculty
# Create your views here.

def index(request):
        facultylist= Faculty.objects.order_by('-id')[:5]
        context= {'facultylist': facultylist,}
        #output= ', '.join([q.faculty_name for q in facultylist])
        return render(request, 'polls/index.html',context)

def detail(request ,faculty_id):
        faculty= get_object_or_404(Faculty, pk=faculty_id)
        return render(request, 'polls/detail.html' , {'faculty': faculty})

def results(request,faculty_id):
        response = "Results %s"
        return HttpResponse(response %faculty_id)
def vote(request,faculty_id):
        return HttpResponse("Voting on %s" %faculty_id)

poll/polls/templates/polls/detail.html
<h1>{{ faculty.faculty_name }}</h1>

<ul>
{% for choice in faculty.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

poll/polls/templates/polls/index.html
{% if facultylist %}

    <ul>
    {% for faculty in facultylist %}
        <li><a href= "{% url 'polls:detail' faculty.id%}">{{ faculty.faculty_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}